dist: bionic
sudo: required
language: cpp
compiler:
  - gcc
python:
  - "3.7"
# Change this to your needs
before_install:
  - sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev libopenmpi2 python3 python3-pip cmake
env:
  - OMP_NUM_THREADS=4
script:
  - pip3 install --user -r requirements.txt
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ctest

